version: '2'
services:
    scadenziariomongo-app:
        image: scadenziariomongo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://scadenziariomongo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=scadenziariomongo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    scadenziariomongo-mongodb:
        extends:
            file: mongodb.yml
            service: scadenziariomongo-mongodb
